### ISSUE TITLE
Error: Cannot find module './.yo-rc.json'

### ISSUE THREAD

**Issue by nottinhill** [mcfly-io/generator-mcfly-ng2#80]
I encounter this problem at first run after clean install:

```
tyrion@kingsland ~/W/saveup> npm run build

> save-up@0.0.1 build /home/tyrion/WebstormProjects/saveup
> webpack --progress --profile --display-error-details --display-cached

module.js:338
    throw err;
          ^
Error: Cannot find module './.yo-rc.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/tyrion/WebstormProjects/saveup/webpack.config.js:15:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/home/tyrion/WebstormProjects/saveup/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/home/tyrion/WebstormProjects/saveup/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Linux 3.13.0-63-generic
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.9
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! save-up@0.0.1 build: `webpack --progress --profile --display-error-details --display-cached`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the save-up@0.0.1 build script 'webpack --progress --profile --display-error-details --display-cached'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the save-up package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --progress --profile --display-error-details --display-cached
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs save-up
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls save-up
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tyrion/WebstormProjects/saveup/npm-debug.log

```

**Comment by nottinhill** [comment]
Issue resolved. My error was: Did move project files manually into another directory after running generator and npm install.
